VDS-3089: Update csvhelper and fix breaking changes
VirtoCommerce/vc-module-price-export-import pull request #65
Opened 2021-10-05 10:57 UTC by pushnitsa

Description: 

--

QA-test: 

Demo-test: 

Download artifact URL:

2021-10-05 11:23 UTC, asvishnyakov requested changes

2021-10-05 11:23 UTC, asvishnyakov commented on src/VirtoCommerce.PriceExportImportModule.Core/Models/ImportConfigurationFactory.cs
> +    public class ImportConfigurationFactory
Sealed

2021-10-14 07:52 UTC, Vectorfield4 commented on tests/VirtoCommerce.PriceExportImportModule.Tests/CsvHelperTests.cs
> +        public async Task TestDoubleBadDataFoundCase()
Why not `Assert.Equal(2, errorCount);`?

2021-10-14 07:52 UTC, Vectorfield4 commented on tests/VirtoCommerce.PriceExportImportModule.Tests/CsvHelperTests.cs
> +        public async Task TestDoubleBadDataFoundCase()
DoubleBadDataFound produces only one error, why? Here https://github.com/VirtoCommerce/vc-module-price-export-import/pull/65/files#diff-78278f2491d16515959638326452e5bcce817ea68865b9b70b8dbfcf0eb7b377R277 we have one error per row.

2023-08-08 09:22 UTC, closed without merging